# Generated by Django 5.0.6 on 2024-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabkraft_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index_offers',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='commands',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='stars',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='review_choice',
        ),
        migrations.AddField(
            model_name='rating',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
