# Generated by Django 5.0.6 on 2024-06-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabkraft_user', '0004_alter_rating_date_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_carousel',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousel'},
        ),
        migrations.AlterModelOptions(
            name='index_categories',
            options={'verbose_name': 'index page category', 'verbose_name_plural': 'index page category'},
        ),
        migrations.AlterModelOptions(
            name='index_top_categories',
            options={'verbose_name': 'top category', 'verbose_name_plural': 'top category'},
        ),
        migrations.AlterModelOptions(
            name='order_products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='setting_values',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Category'},
        ),
    ]
