# Generated by Django 5.0.6 on 2024-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabkraft_user', '0005_alter_index_carousel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_choices',
            name='options_max_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
