# Generated by Django 5.0.6 on 2024-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabkraft_user', '0006_product_choices_options_max_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_sts',
            field=models.CharField(default='NA', max_length=225),
        ),
        migrations.AddField(
            model_name='orders',
            name='rzp_order_id',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
