# Generated by Django 5.0.6 on 2024-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabkraft_user', '0007_orders_payment_sts_orders_rzp_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_sts',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='orders',
            name='rzp_order_id',
            field=models.CharField(default='', max_length=225),
        ),
    ]
