# Generated by Django 5.0.6 on 2024-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabkraft_user', '0008_alter_orders_payment_sts_alter_orders_rzp_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
